# -*- coding: utf-8 -*-
"""LectureNoteDownload.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aE4KuvnzlfpXyd1fefTsj_jqoHnNkqxy
"""

from urllib import request
from bs4 import BeautifulSoup
import re

url=r'http://u.math.biu.ac.il/~solomyb/TEACH/18/GMT/index.html'
link=r'http://u.math.biu.ac.il/~solomyb/TEACH/18/GMT/'

# proxy={'http':'http://localhost:80'}
headers = ("User-Agent"," Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36")  #这里模拟浏览器  
opener = request.build_opener()  
opener.addheaders = [headers]
request.install_opener(opener)
# 添加 header 模拟浏览器, 可兼容 urlretrieve.

contents = request.urlopen(url).read().decode()
soup = BeautifulSoup(contents,"html.parser")
n=1
for tag in soup.find_all('a'): 
    pdf = tag.get('href')
    pdfurl = link+pdf
    print(pdfurl+"\n")
    pdfdir = 'C:/Users/whzec/Desktop/'+pdf
    request.urlretrieve(pdfurl,pdfdir)
    n=n+1

# urlretrieve 用来保存文件, py3 在 urllib.request内, py2在urllib

