# -*- coding: utf-8 -*-
"""replacetxt.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eXL6qy3DWAte-dKIzPmKEaKpBviXpLTK

# 文件的读取与写入

首先我们给出一个非常有用的例子, 即文件的替换.
"""

# replace some words by python
import re
f=open(r'C:\Users\whzec\Desktop\1.md','r') #加上r是为了能使用反斜杠的地址,否则使用斜杠,或者双反斜杠.
alllines=f.readlines()
f.close()
f=open(r'C:\Users\whzec\Desktop\1.md','w+')
for eachline in alllines:
    a=re.sub('List','cctvcctv',eachline)
    f.writelines(a)
f.close()

